### ISSUE TITLE
error al ejecutar

### ISSUE THREAD

**Issue by dguillermo** [gearcapitan/WPScanPlugin-Static#1]
Traceback (most recent call last):
  File "~/WPScanPlugin-Static/WPStaticGPT.py", line 8, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "~/WPScanPlugin-Static/main.py", line 26, in <module>
    subprocess.run(["python3", "WPStaticGPT.py", url], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'WPStaticGPT.py', 'url.com']' returned non-zero exit status 1.

**Comment by gearcapitan** [comment]
Ejecuta pls pip3 install -r requirements.txt

**Comment by dguillermo** [comment]
Lo mismo.

Preparando... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Por favor, ingrese la URL del sitio web:: url.com 
Traceback (most recent call last):
  File "~/WPScanPlugin-Static/WPStaticGPT.py", line 8, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "~/WPScanPlugin-Static/main.py", line 26, in <module>
    subprocess.run(["python3", "WPStaticGPT.py", url], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'WPStaticGPT.py', 'url.com']' returned non-zero exit status 1.

/WPScanPlugin-Static$ ../bin/pip3 list
Package            Version
------------------ ---------
beautifulsoup4     4.12.2
certifi            2022.12.7
charset-normalizer 3.1.0
idna               3.4
markdown-it-py     2.2.0
mdurl              0.1.2
pip                23.0.1
psutil             5.9.5
Pygments           2.15.1
requests           2.30.0
rich               13.3.5
setuptools         66.1.1
soupsieve          2.4.1
urllib3            2.0.2

Te añado un pip list, para que compruebes, el error me lo da tanto en un entorno virtual sólo para esto tanto en otra máquina diferente

**Comment by gearcapitan** [comment]
pues vas de nuevo, 

pip3 uninstall psutil

pip3 install psutil


recuerda usar pip3 y python3, python3 main.py

**Comment by dguillermo** [comment]
Nada, mismo problema

**Comment by gearcapitan** [comment]
pues entonces toca lo siguiente: 

virtualenv venv

source venv/bin/activate

pip3 install -r requirements.txt

python3 main.py

**Comment by dguillermo** [comment]
dguillermo@keymaker:~$ python3 -m venv /home/dguillermo/WPScanPlugin/ 
dguillermo@keymaker:~$ cd /home/dguillermo/WPScanPlugin/WPScanPlugin-Static/
dguillermo@keymaker:~/WPScanPlugin/WPScanPlugin-Static$ source ../bin/activate
(WPScanPlugin) dguillermo@keymaker:~/WPScanPlugin/WPScanPlugin-Static$ pip3 install -r requirements.txt
Requirement already satisfied: rich in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (13.3.5)
Requirement already satisfied: psutil in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (5.9.5)
Requirement already satisfied: requests in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.30.0)
Requirement already satisfied: beautifulsoup4 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from rich->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from rich->-r requirements.txt (line 1)) (2.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from requests->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: soupsieve>1.2 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from beautifulsoup4->-r requirements.txt (line 4)) (2.4.1)
Requirement already satisfied: mdurl~=0.1 in /home/dguillermo/WPScanPlugin/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->-r requirements.txt (line 1)) (0.1.2)
(WPScanPlugin) dguillermo@keymaker:~/WPScanPlugin/WPScanPlugin-Static$ python3 main.py 
╭─────────────────────────────────────────╮
│ -Written by Gearcapitan with Chatgptv4- │
╰─────────────────────────────────────────╯
Preparando... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Por favor, ingrese la URL del sitio web:: dominio.es 
Archivos descargados: 1 | Velocidad de descarga: 0.00 KB/s | Tiempo transcurrido: 00:04
Traceback (most recent call last):
  File "/home/dguillermo/WPScanPlugin/WPScanPlugin-Static/WPStaticGPT.py", line 161, in <module>
    find_plugins(download_directory)
  File "/home/dguillermo/WPScanPlugin/WPScanPlugin-Static/WPStaticGPT.py", line 146, in find_plugins
    print("[blink][bold red]Ningún plugin encontrado[/bold][/blink]")
  File "/home/dguillermo/WPScanPlugin/lib/python3.11/site-packages/rich/__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dguillermo/WPScanPlugin/lib/python3.11/site-packages/rich/console.py", line 1673, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dguillermo/WPScanPlugin/lib/python3.11/site-packages/rich/console.py", line 1537, in _collect_renderables
    self.render_str(
  File "/home/dguillermo/WPScanPlugin/lib/python3.11/site-packages/rich/console.py", line 1429, in render_str
    rich_text = render_markup(
                ^^^^^^^^^^^^^^
  File "/home/dguillermo/WPScanPlugin/lib/python3.11/site-packages/rich/markup.py", line 161, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/bold]' at position 41 doesn't match any open tag
Traceback (most recent call last):
  File "/home/dguillermo/WPScanPlugin/WPScanPlugin-Static/main.py", line 26, in <module>
    subprocess.run(["python3", "WPStaticGPT.py", url], check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'WPStaticGPT.py', 'dominio.es']' returned non-zero exit status 1.
(WPScanPlugin) dguillermo@keymaker:~/WPScanPlugin/WPScanPlugin-Static$
